runtime: python39

handlers:
- url: /static/
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  APPENGINE_URL: https://lungdiseasedetection.et.r.appspot.com
  DJANGO_SETTINGS_MODULE: 'mywebsite.settings'