pip install Django==1.11.29
pip install django-widget-tweaks
pip install keras
pip install tensorflow
pip install Pillow
pip install numpy
pip install matplotlib
pip install psycopg2-binary==2.8.6
pip install Keras-Preprocessing
pip install pytz
python3.9 manage.py collectstatic