pip install Django==1.11.29
pip install django-widget-tweaks
pip install keras
pip install tensorflow
pip install mysqlclient
pip install Pillow
pip install numpy
pip install matplotlib
python3.7 manage.py collecstatic