# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(null=True, upload_to='')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('waktu_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('category', models.CharField(choices=[('Pneumonia', 'Pneumonia'), ('Tuberculosis', 'Tuberculosis'), ('COVID19', 'COVID19'), ('Normal', 'Normal')], max_length=100)),
            ],
        ),
    ]
