# Generated by Django 4.2.3 on 2023-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gambar', models.ImageField(null=True, upload_to='')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('waktu_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('category', models.CharField(choices=[('Pneumonia', 'Pneumonia'), ('Tuberculosis', 'Tuberculosis'), ('COVID19', 'COVID19'), ('Normal', 'Normal')], max_length=100)),
            ],
        ),
    ]
